name: Deploy Jupyter Notebook to Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Jupyter
      run: |
        pip install jupyter nbconvert[webpdf]
        
    - name: Create docs directory
      run: mkdir -p docs
        
    - name: Convert notebooks to HTML
      run: |
        # Convert all .ipynb files to HTML
        for notebook in *.ipynb; do
          if [ -f "$notebook" ]; then
            echo "Converting $notebook"
            jupyter nbconvert --to html --output-dir=docs "$notebook"
          fi
        done
        
    - name: Create index page
      run: |
        cat > docs/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
            <title>Mis Notebooks</title>
            <meta charset="UTF-8">
            <style>
                body { font-family: Arial, sans-serif; margin: 40px; }
                h1 { color: #333; }
                .notebook { 
                    background: #f5f5f5; 
                    padding: 15px; 
                    margin: 10px 0; 
                    border-radius: 5px; 
                }
                .notebook a { 
                    text-decoration: none; 
                    color: #0066cc; 
                    font-weight: bold; 
                }
            </style>
        </head>
        <body>
            <h1>📚 Mis Jupyter Notebooks</h1>
        EOF
        
        # Add links to all HTML files
        for html in docs/*.html; do
          if [ -f "$html" ] && [ "$(basename "$html")" != "index.html" ]; then
            filename=$(basename "$html")
            name="${filename%.*}"
            echo "<div class='notebook'>" >> docs/index.html
            echo "<a href='$filename'>📓 $name</a>" >> docs/index.html
            echo "</div>" >> docs/index.html
          fi
        done
        
        echo "</body></html>" >> docs/index.html
        
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
