```yaml
name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Versión reciente de Python
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbformat==5.10.4 nbconvert==7.16.6 pandas xlsxwriter ipywidgets requests

      - name: Create build directory
        run: mkdir -p build

      - name: Convert Notebook to HTML
        run: |
          jupyter nbconvert --to html --output-dir build your_notebook.ipynb
        continue-on-error: true # Continúa si hay errores en la conversión

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './build' # Directorio con el HTML generado

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
```
